FROM ubuntu:14.04
MAINTAINER Ayoubensalem 
LABEL Description="Dockerfile for mean stack"

# Exposing PORTS : 3000(Nodejs), 27017(MongoDB), 35279(LiveReload)
EXPOSE 3000 27017 35279

# install pre-requisites and essential packaes 
RUN apt-get -q update && apt-get install -y -qq \
	git \
	curl \
	ssh \
	gcc \
	make \
	build-essential \
	sudo \
	apt-utils \
	&& apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Nodejs
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - \
	&& apt-get install -y -q nodejs \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install --quiet -g bower gulp \
	&& npm cache clean 























